---
title: "Initial Analyses"
author: "Shomit Ghosh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simple Analysis - MNL (FULL)

Load data and packages

```{r}
load("cleaned.RData")
load("acq.RData")
load("churn.RData")
load("xsell.RData")
load("upsell.RData")
```

```{r}
library(caret)
library(nnet)
library(xgboost)
library(ggplot2)
library(DMwR)
library(dplyr)
library(randomForest)
library(glmnet)
```

```{r}
#Test regression
final <- full12[, !(names(full12) %in% c("reaction", "customer_notCity", "customer_residential","customer_highRise","customer_urban_pop","customer_householdSize","customer_fiberAvail_duration", "BB_downloadSpeed_current", "BB_downloadSpeed_best", "CampaignName", "CampaignType", "StrategicGoal", "decision_date", "reward_date","customer_mktFocus"))] #remove reaction, keep dhlv

set.seed(100)
train_rows_clean <- createDataPartition(final$delta_hlv, p = 0.8, list = FALSE)
train_full <- final[train_rows_clean,]
test_full <- final[-train_rows_clean,]

train_full <- subset(train_full, subset = train_full$delta_hlv > 2800 | train_full$delta_hlv < -800)
test_full <- subset(test_full, subset = test_full$delta_hlv > 2800 | test_full$delta_hlv < -800)

lm_trial <- lm(data = train_full, delta_hlv ~.)
preds_trial <- predict(lm_trial, newdata = test_full)

plot(preds_trial ~ test_full$delta_hlv)
```

```{r}
final <- full12[, !(names(full12) %in% c("delta_hlv", "customer_notCity", "customer_residential","customer_highRise","customer_urban_pop","customer_householdSize","customer_fiberAvail_duration", "BB_downloadSpeed_current", "BB_downloadSpeed_best", "CampaignName", "CampaignType", "StrategicGoal", "decision_date", "reward_date",""))]
final <- droplevels(final)
final$reaction <- relevel(final$reaction, ref = "No Effect")
```

Split data

```{r}
set.seed(100)
train_rows_clean <- createDataPartition(final$reaction, p = 0.8, list = FALSE)
train_full <- final[train_rows_clean,]
test_full <- final[-train_rows_clean,]

train_full <- train_full %>%
  group_by(reaction) %>%
  sample_n(size = 1000, replace = TRUE) %>%
  ungroup()
```

Feature selection - LASSO

```{r}
fitControl <- trainControl(method = 'repeatedcv', number = 5, repeats = 3, verboseIter = TRUE)
lass_full <- train(reaction ~.,
                   data = train_full,
                   method = 'glmnet',
                   tuneGrid = expand.grid(alpha = 1,
                                          lambda = seq(0.01,1, length = 100)),
                   trControl = fitControl)

preds_lass <- predict(lass_full, newdata = test_full)
conf_matrix_lasso_full <- confusionMatrix(data = preds_lass, reference = test_full$reaction)

plot(lass_full$finalModel, xvar = "lambda", label = TRUE)
plot(lass_full$finalModel, xvar = "dev", label = TRUE)
plot(varImp(lass_full, scale = TRUE))

```

Model training

```{r}
set.seed(100)
mnl_full <- multinom(data = train_full, reaction ~ mktSize_proxy + strat_new + customer_presence)
```

Model test

```{r}
preds_mnl_full <- predict(mnl_full, newdata = test_full)
conf_matrix_mnl_full <- confusionMatrix(data = preds_mnl_full, reference = test_full$reaction)

```

## Simple Analysis - RF (FULL)

```{r}
set.seed(100)
rf_full <- randomForest(data = train_full, reaction ~ mktSize_proxy + strat_new + customer_presence, do.trace = TRUE)
preds_rf_full <- predict(rf_full, newdata = test_full)
conf_matrix_rf_full <- confusionMatrix(data = preds_rf_full, reference = test_full$reaction)
```

## Simple Analysis - MNL (Acq)

```{r}
acq <- acq[, !(names(full12) %in% c("delta_hlv", "customer_notCity", "customer_residential","customer_highRise","customer_urban_pop","customer_householdSize","customer_fiberAvail_duration", "BB_downloadSpeed_current", "BB_downloadSpeed_best", "CampaignName", "CampaignType", "StrategicGoal", "decision_date", "reward_date",""))]
```

```{r}
# split data
set.seed(100)
train_rows_acq <- createDataPartition(acq$reaction, p = 0.8, list = FALSE)
train_acq <- acq[train_rows_acq,]
test_acq <- acq[-train_rows_acq,]

#train_acq <- train_acq %>%
  #group_by(reaction) %>%
  #sample_n(size = 1000, replace = TRUE) %>%
  #ungroup()
```

```{r}
set.seed(100)
mnl_acq <- multinom(data = train_acq, reaction ~ .)
```

```{r}
preds_mnl_acq <- predict(mnl_acq, newdata = test_acq)
conf_matrix_mnl_acq <- confusionMatrix(data = preds_mnl_acq, reference = test_acq$reaction)
```
